// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UlfenDk.EnergyAssistant.Database;

#nullable disable

namespace UlfenDk.EnergyAssistant.Migrations
{
    [DbContext(typeof(EnergyAssistantContext))]
    partial class EnergyAssistantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("UlfenDk.EnergyAssistant.Database.EnergyUsageRecord", b =>
                {
                    b.Property<long>("EnergyUsageRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Hour")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EnergyUsageRecordId");

                    b.HasIndex("Hour");

                    b.ToTable("Usages");
                });

            modelBuilder.Entity("UlfenDk.EnergyAssistant.Database.SpotPriceRecord", b =>
                {
                    b.Property<long>("SpotPriceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Hour")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrediction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RawPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReducedPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegularPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpotPriceRecordId");

                    b.HasIndex("Hour");

                    b.ToTable("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
